server:
  port: 8001
spring:
  application:
    name: "AuthService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: auth_db
    schema: public
    username: auth_be_user
    password: LaNtrYSOctIsMycionAlPTiCKEYema