server:
  port: 8001
spring:
  application:
    name: "AuthService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: ${SPRING_DATASOURCE_HOST}
    port: ${SPRING_DATASOURCE_PORT}
    database: ${SPRING_DATASOURCE_DATABASE}
    schema: ${SPRING_DATASOURCE_SCHEMA}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}